# Pipeline name
name: Basketball Dataset Pipeline
# Pipeline execution steps
steps:
# check for new teams
  - kernel: wyattowalsh/basketball-dataset-update-teams
  - status: 5s
  # check for new players
  - kernel: wyattowalsh/basketball-dataset-update-players
  - status: 5s
# get additional team/player information
#   - kernel: wyattowalsh/basketball-dataset-update-teams
