name: sports-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - nbdime ### Utilities 
  - pip
  - python
  - ipykernel
  - nb_conda
  - jupyter_contrib_nbextensions
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - yapf
  - isort 

